name: Test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v4
      - name: installing bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install dependencies
        run: bun ci
      - name: Run tests
        run: bun test
